# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

### UI strings for the MR1 onboarding / multistage about:welcome
### Various strings use a non-breaking space to avoid a single dangling /
### widowed word, so test on various window sizes if you also want this.

## Welcome page strings

onboarding-welcome-header = 欢迎您使用 { -brand-short-name }
onboarding-start-browsing-button-label = 开始浏览
onboarding-not-now-button-label = 暂不执行
mr1-onboarding-get-started-primary-button-label = 开始操作

## Custom Return To AMO onboarding strings

return-to-amo-subtitle = 很好，您已获得 { -brand-short-name }
# <img data-l10n-name="icon"/> will be replaced with the icon belonging to the extension
#
# Variables:
#   $addon-name (String) - Name of the add-on
return-to-amo-addon-title = 现在，我们将为您配置 <img data-l10n-name="icon"/> <b>{ $addon-name }</b>。
return-to-amo-add-extension-label = 添加扩展程序
return-to-amo-add-theme-label = 添加主题
return-to-amo-theme-install-complete-label = 主题已安装完成
return-to-amo-extension-install-complete-label = 扩展程序已安装完成

##  Variables: $addon-name (String) - Name of the add-on to be installed

mr1-return-to-amo-subtitle = 请向 { -brand-short-name } 致意
mr1-return-to-amo-addon-title = 您已拥有快速、私密的浏览器，触手可及。现在，您可以添加 <b>{ $addon-name }</b>，并使用 { -brand-short-name } 执行更多操作。
mr1-return-to-amo-add-extension-label = 添加 { $addon-name }

## Multistage onboarding strings (about:welcome pages)

# Aria-label to make the "steps" of multistage onboarding visible to screen readers.
# Variables:
#   $current (Int) - Number of the current page
#   $total (Int) - Total number of pages

onboarding-welcome-steps-indicator-label =
  .aria-label = 进度情况：步骤 { $current }，共 { $total } 步


# This button will open system settings to turn on prefers-reduced-motion
mr1-onboarding-reduce-motion-button-label = 关闭动画效果

# String for the Firefox Accounts button
mr1-onboarding-sign-in-button-label = 登录

# The primary import button label will depend on whether we can detect which browser was used to download Firefox.
# Variables:
#   $previous (Str) - Previous browser name, such as Edge, Chrome
mr1-onboarding-import-primary-button-label-attribution = 从 { $previous } 导入

mr1-onboarding-theme-header = 将其定制为您专属
mr1-onboarding-theme-subtitle = 使用主题个性化设置 { -brand-short-name }。
mr1-onboarding-theme-secondary-button-label = 暂不执行

# System theme uses operating system color settings
mr1-onboarding-theme-label-system = 系统主题

mr1-onboarding-theme-label-light = 浅色主题
mr1-onboarding-theme-label-dark = 深色主题
# "Alpenglow" here is the name of the theme, and should be kept in English.
mr1-onboarding-theme-label-alpenglow = Alpenglow

onboarding-theme-primary-button-label = 完成

## Accessible labels for the icon-only play/pause toggle that controls animated
## illustrations on the onboarding screen. The button replaces the animation
## with a static image when clicked.

onboarding-animation-pause-button =
  .aria-label = 暂停动画
onboarding-animation-play-button =
  .aria-label = 播放动画

## Please make sure to split the content of the title attribute into lines whose
## width corresponds to about 40 Latin characters, to ensure that the tooltip
## doesn't become too long. Line breaks will be preserved when displaying the
## tooltip.

# Tooltip displayed on hover of system theme
mr1-onboarding-theme-tooltip-system =
  .title =
    请遵循操作系统的主题设置，
    应用于按钮、菜单和窗口。

# Input description for system theme
mr1-onboarding-theme-description-system =
  .aria-description =
    请遵循操作系统的主题设置，
    应用于按钮、菜单和窗口。

# Tooltip displayed on hover of light theme
mr1-onboarding-theme-tooltip-light =
  .title =
    请为按钮、菜单和窗口
    使用浅色主题。

# Input description for light theme
mr1-onboarding-theme-description-light =
  .aria-description =
    请为按钮、菜单和窗口
    使用浅色主题。

# Tooltip displayed on hover of dark theme
mr1-onboarding-theme-tooltip-dark =
  .title =
    请为按钮、菜单和窗口
    使用深色主题。

# Input description for dark theme
mr1-onboarding-theme-description-dark =
  .aria-description =
    请为按钮、菜单和窗口
    使用深色主题。
# Tooltip displayed on hover of Alpenglow theme
mr1-onboarding-theme-tooltip-alpenglow =
  .title =
    为按钮、菜单和窗口使用动态的、多彩的主题。

# Input description for Alpenglow theme
mr1-onboarding-theme-description-alpenglow =
  .aria-description =
    为按钮、菜单和窗口使用动态的、多彩的主题。

# Selector description for default themes
mr2-onboarding-default-theme-label = 请探索默认主题。

## Strings for Thank You page

mr2-onboarding-thank-you-header = 感谢您选择我们
mr2-onboarding-thank-you-text = { -brand-short-name } 是一个由非营利组织支持的独立浏览器。我们共同致力于让网络更加安全、健康、私密。
mr2-onboarding-start-browsing-button-label = 开始浏览

## Multistage live language reloading onboarding strings (about:welcome pages)
##
## The following language names are generated by the browser's Intl.DisplayNames API.
##
## Variables:
##   $negotiatedLanguage (String) - The name of the langpack's language, e.g. "Español (ES)"
##   $systemLanguage (String) - The name of the system language, e.g "Español (ES)"
##   $appLanguage (String) - The name of the language shipping in the browser build, e.g. "English (EN)"

onboarding-live-language-header = 请选择您的语言

mr2022-onboarding-live-language-text = { -brand-short-name } 使用您的语言进行交流

mr2022-language-mismatch-subtitle = 感谢我们的社区，{ -brand-short-name } 已被翻译成超过90种语言。看起来您的系统正在使用 { $systemLanguage }，而 { -brand-short-name } 正在使用 { $appLanguage }。

onboarding-live-language-button-label-downloading = 正在下载 { $negotiatedLanguage } 的语言包…
onboarding-live-language-waiting-button = 正在获取可用语言…
onboarding-live-language-installing = 正在安装 { $negotiatedLanguage } 的语言包…

mr2022-onboarding-live-language-switch-to = 切换到 { $negotiatedLanguage }
mr2022-onboarding-live-language-continue-in = 继续使用 { $appLanguage }

onboarding-live-language-secondary-cancel-download = 取消
onboarding-live-language-skip-button-label = 跳过

## Firefox 100 Thank You screens

# "Hero Text" displayed on left side of welcome screen. This text can be
# formatted to span multiple lines as needed. The <span data-l10n-name="zap">
fx100-thank-you-hero-text =
  100
  感谢
  <span data-l10n-name="zap">您们</span>
fx100-thank-you-subtitle = 这是我们的第100次发布！感谢您帮助我们构建一个更好、更健康的互联网。
fx100-thank-you-pin-primary-button-label = { PLATFORM() ->
    [macos] 将 { -brand-short-name } 保留在程序坞中
   *[other] 将 { -brand-short-name } 固定到任务栏
}

fx100-upgrade-thanks-header = 100 次感谢
# </span> in this string allows a "zap" underline style to be automatically
fx100-upgrade-thank-you-body = 这是 { -brand-short-name } 的第100次发布。感谢<em>您</em>帮助我们构建一个更好、更健康的互联网。
# added to the text inside it. "Yous" should stay inside the zap span, but
fx100-upgrade-thanks-keep-body = 这是我们的第100次发布！感谢您成为我们社区的一员。请将 { -brand-short-name } 保持在随手可及之处，以备未来之需。

mr2022-onboarding-secondary-skip-button-label = 跳过此步骤

# "Thank" can be put inside instead if there's no "you" in the translation.

# The English text would normally be "100 Thank-Yous" i.e., plural noun, but for
mr2022-onboarding-easy-setup-primary-button-label = 保存并继续
# aesthetics of splitting it across multiple lines, the hyphen is omitted.
mr2022-onboarding-easy-setup-set-default-checkbox-label = 将 { -brand-short-name } 设置为默认浏览器
# Message shown with a start-browsing button. Emphasis <em> should be for "you"
mr2022-onboarding-easy-setup-import-checkbox-label = 从先前的浏览器导入

# but "Thank" can be used instead if there's no "you" in the translation.

# Message shown with either a pin-to-taskbar or set-default button.
## MR2022 New User Easy Setup screen strings
# Primary button string used on new user onboarding first screen showing multiple actions such as Set Default, Import from previous browser.
# Set Default action checkbox label used on new user onboarding first screen
mr2022-onboarding-welcome-pin-header = 启动一个令人惊叹的互联网
# Import action checkbox label used on new user onboarding first screen
mr2022-onboarding-welcome-pin-subtitle = 只需单击一下，即可从任何位置启动 { -brand-short-name }。每次您这样做，都是在选择一个更加开放和独立的网络。
## MR2022 New User Pin Firefox screen strings
mr2022-onboarding-pin-primary-button-label = { PLATFORM() ->
    [macos] 将 { -brand-short-name } 保留在程序坞中
   *[other] 将 { -brand-short-name } 固定到任务栏
}

# Title used on about:welcome for new users when Firefox is not pinned.
mr2022-onboarding-pin-primary-button-label-msix = 将 { -brand-short-name } 固定到任务栏和开始菜单

# In this context, open up is synonymous with "Discover".

# The metaphor is that when they open their Firefox browser, it helps them discover an amazing internet.
mr2022-onboarding-existing-pin-header = 感谢您喜爱 { -brand-product-name }
# If this translation does not make sense in your language, feel free to use the word "discover."
mr2022-onboarding-existing-pin-subtitle = 只需单击一下，即可从任何位置启动一个更健康的互联网。我们的最新更新充满了我们认为您会喜爱的新功能。
# Subtitle is used on onboarding page for new users page when Firefox is not pinned
mr2022-onboarding-existing-set-default-only-subtitle = 当您在网络上飞速浏览时，请使用一款保护您隐私的浏览器。我们的最新更新充满了您所喜爱的事物。
mr2022-onboarding-existing-pin-checkbox-label = 同时添加 { -brand-short-name } 的隐私浏览

# Primary button string used on welcome page for when Firefox is not pinned.

# Primary button string used on welcome page for when Firefox is not pinned on MSIX
mr2022-onboarding-set-default-title = 将 { -brand-short-name } 设为您首选的浏览器
mr2022-onboarding-set-default-primary-button-label = 将 { -brand-short-name } 设置为默认浏览器
## MR2022 Existing User Pin Firefox Screen Strings
mr2022-onboarding-set-default-subtitle = 请使用一个由非营利组织支持的浏览器。当您在网络上飞速浏览时，我们将捍卫您的隐私。
## MR2022 Get Started screen strings.
## These strings will be used on the welcome page
## when Firefox is already set to default and pinned.

# When translating "zip", please feel free to pick a verb that signifies movement and/or exploration
# and makes sense in the context of navigating the web.
mr2022-onboarding-get-started-primary-subtitle = 我们的最新版本围绕您而构建，比以往任何时候都更容易让您在网络上快速穿梭。它充满了我们认为您会喜爱的功能。
mr2022-onboarding-get-started-primary-button-label = 在数秒内完成设置

mr2022-onboarding-import-primary-button-label-no-attribution = 从先前浏览器导入

## MR2022 Multistage Mobile Download screen strings

mr2022-onboarding-mobile-download-cta-text = 请扫描二维码以获取移动版 { -brand-product-name }，或<a data-l10n-name="download-label">向您发送下载链接。</a>
mr2022-onboarding-no-mobile-download-cta-text = 请扫描二维码以获取移动版 { -brand-product-name }。

## MR2022 Upgrade Dialog screens
## Pin private window screen shown only for users who don't have Firefox private pinned

mr2022-upgrade-onboarding-pin-private-window-header = 请通过单击获取专用浏览自由
mr2022-upgrade-onboarding-pin-private-window-subtitle = 无已保存的 Cookie 或历史记录，直接在您的桌面上。请像无人观看一样进行浏览。
mr2022-upgrade-onboarding-pin-private-window-primary-button-label = { PLATFORM() ->
    [macos] 将 { -brand-short-name } 专用浏览保留在程序坞中
   *[other] 将 { -brand-short-name } 专用浏览固定到任务栏
}

## MR2022 Privacy Segmentation screen strings

mr2022-onboarding-privacy-segmentation-title = 我们始终尊重您的隐私
mr2022-onboarding-privacy-segmentation-subtitle = 从智能建议到更智能的搜索，我们正在持续致力于创建更好、更具个性化的 { -brand-product-name }。
mr2022-onboarding-privacy-segmentation-text-cta = 当我们提供利用您的数据来增强您浏览体验的新功能时，您希望看到什么？
mr2022-onboarding-privacy-segmentation-button-primary-label = 使用 { -brand-product-name } 推荐
mr2022-onboarding-privacy-segmentation-button-secondary-label = 显示详细信息

## MR2022 Multistage Gratitude screen strings

mr2022-onboarding-gratitude-title = 您正在帮助我们构建更美好的网络
mr2022-onboarding-gratitude-subtitle = 感谢您使用由 Mozilla 基金会支持的 { -brand-short-name }。在您的支持下，我们正致力于让互联网更加开放、易于访问，并更好地服务于每一个人。
mr2022-onboarding-gratitude-primary-button-label = 查看新增内容
mr2022-onboarding-gratitude-secondary-button-label = 开始浏览

## Onboarding spotlight for infrequent users

onboarding-infrequent-import-title = 请在此感到宾至如归
onboarding-infrequent-import-subtitle = 无论您是在安顿下来还是只是路过，请记住您可以导入您的书签、密码等。
onboarding-infrequent-import-primary-button = 导入到 { -brand-short-name }

## MR2022 Illustration alt tags
## Descriptive tags for illustrations used by screen readers and other assistive tech

mr2022-onboarding-pin-image-alt =
  .aria-label = 一位正在笔记本电脑上工作的人，周围环绕着星星和花朵
mr2022-onboarding-default-image-alt =
  .aria-label = 一个人拥抱 { -brand-product-name } 标志
mr2022-onboarding-import-image-alt =
  .aria-label = 一个人踩着滑板，带有一盒软件图标
mr2022-onboarding-mobile-download-image-alt =
  .aria-label = 青蛙在荷叶上跳跃，中央有一个用于下载移动版 { -brand-product-name } 的二维码
mr2022-onboarding-pin-private-image-alt =
  .aria-label = 魔杖使 { -brand-product-name } 专用浏览标志从帽子中显现
mr2022-onboarding-privacy-segmentation-image-alt =
  .aria-label = 浅肤色和深肤色的手击掌
mr2022-onboarding-gratitude-image-alt =
  .aria-label = 透过窗户看到的日落景色，窗台上有狐狸和一盆室内植物

## Device migration onboarding

onboarding-device-migration-image-alt =
  .aria-label = 笔记本电脑屏幕上一只狐狸在挥手。笔记本电脑连接着一个鼠标。
onboarding-device-migration-title = 欢迎回来！
onboarding-device-migration-subtitle2 = 请登录您的账户，以便将您的书签、密码和历史记录带到您的新设备上。
onboarding-device-migration-primary-button-label = 登录

## Add-ons Picker screen

amo-picker-title = 自定义您的 { -brand-short-name }
amo-picker-subtitle = 扩展程序就像您浏览器的应用程序，它们让您能够保护密码、下载视频、查找优惠、屏蔽烦人的广告、更改浏览器的外观等等。
amo-picker-install-button-label = 添加到 { -brand-short-name }
amo-picker-install-complete-label = 已安装
amo-picker-collection-link = 探索更多附加组件

## The following screens have been updated to use security and privacy focused strings:

# Easy setup screen
onboarding-easy-setup-security-and-privacy-title = 我们热爱保障您的安全
onboarding-easy-setup-security-and-privacy-subtitle = 我们由非营利组织支持的浏览器有助于阻止公司在网络上秘密跟踪您的行为。

# Mobile download screen
onboarding-mobile-download-security-and-privacy-title = 在设备之间切换时请保持加密状态
onboarding-mobile-download-security-and-privacy-subtitle = 当您完成同步后，{ -brand-short-name } 会对您的密码、书签等内容进行加密。此外，您还可以从其他设备获取标签页。

# Gratitude screen
onboarding-gratitude-security-and-privacy-title = { -brand-short-name } 为您提供支持
onboarding-gratitude-security-and-privacy-subtitle = 感谢您使用由 Mozilla 基金会支持的 { -brand-short-name }。在您的支持下，我们正致力于让互联网对每个人来说更安全、更易于访问。

# Sign up or Sign in screen
onboarding-sign-up-title = 在设备之间同步您的数据
onboarding-sign-up-description = 请注册一个账户，您所有的重要信息——密码、书签等——将被安全地存储，并在您登录任何设备时可用。
onboarding-sign-up-button = 注册或登录
onboarding-sign-up-secondary-button = 开始浏览

## New user time and familiarity survey strings

onboarding-new-user-time-based-survey-title = 您使用 { -brand-short-name } 多长时间了？
onboarding-new-user-familiarity-based-survey-title = 您对 { -brand-short-name } 的熟悉程度如何？

onboarding-new-user-survey-subtitle = 您的反馈有助于让 { -brand-short-name } 更加优秀。

# When translating "next" it means the next screen in onboarding.
onboarding-new-user-survey-next-button-label = 下一步
onboarding-new-user-survey-legal-link-label = 通过选择“{ onboarding-new-user-survey-next-button-label }”，您同意 { -brand-product-name } 的 <a data-l10n-name="privacy_notice">隐私声明</a>

# When translating "brand new" it means completely new.
onboarding-new-user-survey-time-based-option-1 = 我是全新的用户
onboarding-new-user-survey-time-based-option-2 = 少于 1 个月
onboarding-new-user-survey-time-based-option-3 = 多于 1 个月，经常使用
onboarding-new-user-survey-time-based-option-4 = 多于 1 个月，偶尔使用
# When translating "brand new" it means completely new.
onboarding-new-user-survey-familiarity-based-option-1 = 我是全新的用户
onboarding-new-user-survey-familiarity-based-option-2 = 我曾使用过一些
onboarding-new-user-survey-familiarity-based-option-3 = 我对此非常熟悉
onboarding-new-user-survey-familiarity-based-option-4 = 我过去使用过，但已经有一段时间了

## UI strings for the sidebar and vertical tabs

# New users

# Setup screen for vertical tabs
onboarding-new-tabs-title = 请告诉我们您希望您的标签页位于何处

# Setup screen for vertical tabs - "Switch it up" refers to switching between horizontal and vertical tabs.
onboarding-new-tabs-subtitle = 您可以在侧边栏设置中随时进行切换。

# Setup screen for vertical tabs - too many tabs variation
onboarding-many-tabs-title = 您的标签页，您的方式

# Setup screen for vertical tabs - subtitle for too many tabs variation
onboarding-many-tabs-subtitle = 您是否打开了大量标签页？请尝试将标签页置于侧边，以获得更精简的视图。或者保持经典样式，将标签页置于顶部。您可以随时切换。

# Setup screen for vertical tabs - focused variation
onboarding-focused-tabs-title = 请选择您的标签页布局

# Setup screen for vertical tabs - subtitle for focused variation
onboarding-focused-tabs-subtitle = 为了获得可帮助您保持专注的精简视图，请尝试将标签页置于侧边。或者保持经典样式，将标签页置于顶部。您可以随时切换。

# Text underneath an image used for selecting browser tabs to appear on the side of the browser.
onboarding-new-vertical-tabs-label = 标签页位于侧边

# Text underneath an image used for selecting browser tabs to appear at the top of the browser.
onboarding-new-horizontal-tabs-label = 标签页位于顶部

# Existing users

# Setup screen for vertical tabs for existing users
onboarding-existing-tabs-title = 垂直标签页现已推出

# Setup screen for vertical tabs for existing users
onboarding-existing-tabs-title2 = 向您介绍垂直标签页

# Setup screen for vertical tabs for existing users - "Switch it up" refers to switching between horizontal and vertical tabs.
onboarding-existing-tabs-subtitle = 请尝试将标签页置于侧边。您可以在侧边栏设置中随时进行切换。

# Text underneath an image used for selecting browser tabs to appear on the side of the browser.
onboarding-existing-vertical-tabs-label = 请尝试垂直标签页
onboarding-flair-text = 新功能！

# Text underneath an image used for selecting browser tabs to appear at the top of the browser.
onboarding-existing-horizontal-tabs-label = 保持水平标签页

# All users - Initial setup card

# Tooltip displayed on hover for vertical tabs image
onboarding-vertical-tabs-tooltip =
    .title = 一个浏览器窗口，其中标签页作为 { -brand-shorter-name } 侧边栏的一部分显示在屏幕侧边。

# Description for vertical tabs image
onboarding-vertical-tabs-description =
    .aria-description = 一个浏览器窗口，其中标签页作为 { -brand-shorter-name } 侧边栏的一部分显示在屏幕侧边。

# Tooltip displayed on hover for horizontal tabs image
onboarding-horizontal-tabs-tooltip =
    .title = 一个浏览器窗口，其中标签页显示在顶部。

# Description for horizontal tabs image
onboarding-horizontal-tabs-description =
    .aria-description = 一个浏览器窗口，其中标签页显示在顶部。

# Existing users - additional setup card

# Additional setup card for setting up aichatbot in the sidebar
onboarding-genai-sidebar-title = 请在侧边栏中尝试使用 AI 聊天机器人

# Setup card for setting up AI chatbot in the sidebar; "Providers" refers to AI chatbot providers (e.g. OpenAI, etc). "Switch anytime" refers to allowing the user to switch to a different chatbot.
onboarding-genai-sidebar-subtitle = 汇总网页内容、集思广益、起草消息——一切操作均可在您浏览时进行。您可以从多个提供商中进行选择。您可以随时切换。 <a data-l10n-name="learn-more">了解更多</a>
onboarding-genai-sidebar-primary-button = 请选择聊天机器人
onboarding-genai-sidebar-secondary-button = 开始浏览

## New user onboarding checklist

onboarding-checklist-title = 完成 { -brand-short-name } 的设置
onboarding-checklist-subtitle = 请完成以下步骤，以便充分利用您的浏览体验。
onboarding-checklist-set-default = 将 { -brand-short-name } 设置为默认浏览器
onboarding-checklist-pin = 将 { -brand-short-name } 固定到任务栏
onboarding-checklist-import = 从以前的浏览器导入
onboarding-checklist-extension = 添加扩展
onboarding-checklist-sign-up = 注册或登录您的账户

## Tab Groups feature onboarding strings

tab-groups-onboarding-feature-callout-title = 请尝试使用标签组，以减少杂乱，增强专注
tab-groups-onboarding-feature-callout-subtitle = 您可以通过将一个标签页拖到另一个标签页之上来创建您的第一个组，从而实现有序整理。

# The text "list all tabs" refers to the string tabs-toolbar-list-all-tabs
tab-groups-onboarding-create-group-title-3 = 您可以随时在“列出所有标签页”菜单中找到您的标签组。
tab-groups-onboarding-create-group-no-alltabs-button-title = 您可以通过在地址栏中搜索来找到您的组。

# The text "list all tabs" refers to the string tabs-toolbar-list-all-tabs
tab-groups-onboarding-saved-groups-title-3 = 当您关闭一个标签组后，您可以随时从“列出所有标签页”菜单中将其重新打开。
tab-groups-onboarding-saved-groups-no-alltabs-button-title-2 = 您可以通过在地址栏中搜索来找到您已关闭的组。

# The text "list all tabs" refers to the string tabs-toolbar-list-all-tabs
tab-groups-onboarding-session-restore-title-2 = 您可以随时从“列出所有标签页”菜单中重新打开您的标签组。
tab-groups-onboarding-dismiss = 确定

## Multi Profiles feature onboarding messages

multi-profile-spotlight-title = 向您介绍 { -brand-product-name } 配置文件
multi-profile-spotlight-body = 您可以轻松地在工作浏览和娱乐浏览之间进行切换。配置文件可让您的浏览信息（包括搜索历史记录和密码）完全分离，从而使您保持有序。
multi-profile-spotlight-cta = 创建配置文件

multi-profile-callout-title = 请为工作和娱乐创建不同的配置文件
multi-profile-callout-subtitle = 配置文件可让您将浏览信息（如搜索历史记录和密码）完全分离。
multi-profile-callout-cta = 创建配置文件

## Desktop to Mobile Adoption feature callout strings

# If translating the headline is challenging, consider using a simplified alternative as a reference: 'Sync your browsing with Firefox for mobile.'
desktop-to-mobile-headline = 下载、同步，然后出发！
# The phrase, 'on the go', is used to describe when people are very busy and are traveling from place to place.
desktop-to-mobile-subtitle = 扫描二维码以下载适用于移动设备的 { -brand-product-name }。安装完成后，请选择“同步至移动设备”，以便您在旅途中访问您的密码、书签及其他数据。

dismiss-button-label = 关闭
sync-to-mobile-button-label = 同步至移动设备
desktop-to-mobile-qr-code-alt =
  .aria-label = 用于下载适用于移动设备的 { -brand-product-name } 的二维码

## Fx Backup onboarding: Create Backup spotlight

create-backup-screen-1-title = 您是否正在升级至 11 Windows？让我们备份您的 { -brand-product-name } 数据。
create-backup-screen-1-subtitle = 请在 1–2 分钟内自动保护您的密码、书签及其他数据。
create-backup-screen-1-flair = 推荐
create-backup-learn-more-link = <a data-l10n-name="learn-more-label">了解详情</a>
create-backup-screen-1-sync-label = 与 { -brand-product-name } 同步
create-backup-screen-1-sync-body = 备份所有已登录设备上的数据
create-backup-screen-1-backup-label = 备份至个人计算机
create-backup-screen-1-backup-body = 保存至您的设备或 OneDrive
create-backup-select-tile-button-label = 选择
create-backup-back-button-label = 返回
create-backup-show-fewer =
  .label = 减少显示此类内容
create-backup-screen-2-title = 请选择要备份的 { -brand-product-name } 数据
create-backup-screen-2-subtitle = 仅需一分钟。您的数据将每日备份一次。
# Label for the "Easy setup" backup option
create-backup-screen-2-easy-label = 简便设置
# Preceded by a green check mark indicating that these are included in "Easy setup" backup
create-backup-screen-2-easy-list-1 = 书签、历史记录、设置及其他数据
# Preceded by a red X indicating that these are not included in the "Easy setup" backup
create-backup-screen-2-easy-list-2 = 不包含密码和支付信息
# Preceded by a red X indicating that "Easy setup" backups are not encrypted
create-backup-screen-2-easy-list-3 = 未加密
# Label for the "All data" backup option
create-backup-screen-2-all-label = 全部数据
# Preceded by a green check mark indicating that these are included in the "All data" backup
create-backup-screen-2-all-list-2 = 包含密码和支付信息
# Preceded by a green check mark and shield indicating "All data" backups are encrypted
create-backup-screen-2-all-list-3 = 使用密码进行加密

# Title for a screen asking users to choose a file location
create-backup-screen-3-location = 您希望将备份保存在何处？
# Title for a screen asking users to create a password that will encrypt the backup
create-backup-screen-3-title = 请创建备份文件密码
create-backup-screen-3-subtitle = 此密码为加密您的数据所必需。请将其存储在您能够记住的位置。

# These strings appear in the embedded backup component.

fx-backup-opt-in-header = 选择文件位置
fx-backup-opt-in-filepath-label = 请选择您计划传输至新设备的位置，例如 OneDrive。
fx-backup-opt-in-create-password-label = 请输入密码
fx-backup-opt-in-confirm-btn-label = 继续
fx-backup-opt-in-cancel-btn-label = 返回

## Fx Backup confirmation screen strings

fx-backup-confirmation-screen-title = 您的备份已安排
fx-backup-confirmation-screen-close-button = 关闭

## These strings appear as a confirmation of which items will or won't be included as part of the selected backup method.

fx-backup-confirmation-screen-all-data-item-text-1 = 包含所有浏览数据
fx-backup-confirmation-screen-all-data-item-text-2 = 保存至您的设备
fx-backup-confirmation-screen-all-data-item-text-3 = 已加密并受密码保护

fx-backup-confirmation-screen-easy-setup-item-text-1 = 包含书签、历史记录、设置及其他数据
fx-backup-confirmation-screen-easy-setup-item-text-2 = 保存至您的设备
fx-backup-confirmation-screen-easy-setup-item-text-3 = 不包含密码和支付信息
fx-backup-confirmation-screen-easy-setup-item-subtext-3 = 请前往<a data-l10n-name="settings">设置</a>以包含敏感数据。

fx-backup-confirmation-screen-item-subtext-1 = 您的备份将在几分钟后开始，并每日运行一次。您可以在<a data-l10n-name="settings">设置</a>中查看进度。
fx-backup-confirmation-screen-item-subtext-2 = 如果您需要重新安装，{ -brand-short-name } 将查找您的备份。

## Restore from Backup Flow about:welcome screens

restore-from-backup-secondary-top-button = 从备份恢复
restore-from-backup-title = 让我们将 { -brand-short-name } 恢复至您喜欢的状态
restore-from-backup-subtitle = 请恢复您的所有书签、历史记录及其他数据，以便继续浏览。
restore-from-backup-secondary-button = 不恢复

multiple-backups-info-tile = <strong>检测到多个备份文件。</strong>已选择最近的文件。请在<a data-l10n-name="settings-label">设置</a>中恢复其他配置文件。

## Restored from Backup spotlight

restored-from-backup-success-title = 我们回来了！您的 { -brand-short-name } 数据已恢复。
restored-from-backup-success-with-checklist-subtitle = 您是否希望将您喜爱的注重隐私的浏览器保持在一键可达的位置？
restored-from-backup-success-no-checklist-subtitle = 您可以在<a data-l10n-name="settings">设置</a>中为此设备启用备份。
restored-from-backup-success-with-checklist-primary-button = 保存并继续
restored-from-backup-success-with-checklist-secondary-button = 跳过此步骤
restored-from-backup-success-no-checklist-primary-button = 继续
restored-from-backup-error-title = 嗯，您的备份文件存在问题。
restored-from-backup-error-subtitle = 如果您有其他 { -brand-short-name } 备份文件，请尝试从该文件恢复。<a data-l10n-name="restore-problems">仍遇到问题？</a>
restored-from-backup-error-primary-button = 关闭

## Onboarding Personalization Screen
## A screen shown to users during the onboarding process that asks them two qualifying questions about their use of the browser

onboarding-personalization-title = 自定义您的 { -brand-short-name } 体验
onboarding-personalization-subtitle = 请回答几个问题，我们将为您推荐功能和扩展，以增强您对 { -brand-short-name } 的使用。
onboarding-personalization-use-case-title = 您将使用 { -brand-short-name } 进行哪些活动？
onboarding-personalization-use-case-personal-option = 个人使用
onboarding-personalization-use-case-school-option = 学校使用
onboarding-personalization-use-case-work-option = 工作使用
onboarding-personalization-motivation-title = { -brand-short-name } 的哪些功能对您最为重要？
onboarding-personalization-motivation-privacy-option = 隐私与安全
onboarding-personalization-motivation-productivity-option = 生产力
onboarding-personalization-motivation-other-option = 其他

## Onboarding 2026 brand refresh

onboarding-refresh-pin-set-default-subtitle = 我们自动保护您的数据，并阻止公司监视您的点击行为。
# "safe paws" is a play on "safe hands", meaning you're being well taken care of or protected
# If it doesn’t translate well, you can use the alternative: “You’re safe with Firefox.”
onboarding-refresh-pin-set-default-title = 您处于安全掌控之中
onboarding-refresh-import-subtitle = 请导入您的密码、书签、历史记录及其他数据。
onboarding-refresh-import-title = 让 { -brand-short-name } 更具居家感
onboarding-refresh-onboarding-addons-subtitle = 扩展是允许您自定义 { -brand-short-name } 的小型应用程序。它们可以增强您的隐私保护、提升生产力、改变 { -brand-short-name } 的外观，以及实现更多功能。
# "Give your browsing a boost" means to enhance or improve the browsing experience
onboarding-refresh-onboarding-addons-title = 为您的浏览体验提供助力
onboarding-refresh-sync-subtitle = 请在您登录 { -brand-short-name } 的所有位置获取书签、密码及其他数据。此外，您的数据已加密，因此只有您才能查看。
onboarding-refresh-sync-title = 至任何地点。同步一切。
onboarding-refresh-gratitude-subtitle = 感谢您使用 { -brand-short-name }，作为唯一由非营利组织支持的主流浏览器。凭借您的支持，我们正在致力于使互联网对所有人更加安全且更易访问。
# "has your back" is an idiom suggesting support and protection
onboarding-refresh-gratitude-title = { -brand-short-name } 为您提供支持与保护