[OptionalExtensions]
Recommender=Vantage

extension.0.id=idcac-pub@guus.ninja
extension.0.name=I still don't care about cookies
extension.0.checked=1

extension.1.id={278b0ae0-da9d-4cc6-be81-5aa7f3202672}
extension.1.name=Allow Right-Click
extension.1.checked=1
