[OptionalExtensions]
Recommender=Vantage
Recommender.zh-CN=Vantage

extension.0.id=idcac-pub@guus.ninja
extension.0.name=I still don't care about cookies
extension.0.name.zh-CN=不关心 Cookie
extension.0.checked=1

extension.1.id={9350bc42-47fb-4598-ae0f-825e3dd9ceba}
extension.1.name=Absolute Enable Right Click
extension.1.name.zh-CN=绝对右键
extension.1.checked=1

extension.2.id={b184d107-461b-4cfe-b4ba-771406e90c48}
extension.2.name=Screenshot Tool
extension.2.name.zh-CN=截图工具
extension.2.checked=1

extension.3.id=easyscreenshot@mozillaonline.com
extension.3.name=Easy Screenshot
extension.3.name.zh-CN=网页截图
extension.3.checked=1
