[OptionalExtensions]
Recommender=Vantage

extension.0.id=idcac-pub@guus.ninja
extension.0.name=I still don't care about cookies
extension.0.checked=1

extension.1.id={9350bc42-47fb-4598-ae0f-825e3dd9ceba}
extension.1.name=Absolute Enable Right Click
extension.1.checked=1

extension.2.id={b184d107-461b-4cfe-b4ba-771406e90c48}
extension.2.name=Restore Tabs
extension.2.checked=1
