UN_CLEANUP_USERDATA = 是否刪除您的 $BrandShortName 個人資料（書籤、密碼、設定等）？$\r$\n此操作無法撤消。

WINUPDATER_PAGE_TITLE = 自動更新
WINUPDATER_PAGE_SUBTITLE = 選擇是否安裝背景自動更新元件
WINUPDATER_DESCRIPTION = Vantage WinUpdater 會在背景靜默執行，自動將瀏覽器更新至包含最新安全性修補與功能的新版本，讓您始終使用最新、最安全的瀏覽器。$\r$\n$\r$\n您可以現在安裝，也可以略過並手動管理更新；日後如需移除，可隨時透過 Windows 的「應用」清單（設定 → 應用）解除安裝 Vantage WinUpdater。
WINUPDATER_CHECKBOX_DESC = 安裝用於背景自動更新 Vantage 的 WinUpdater 元件（推薦）
