# WebGL permission prompt
# LOCALIZATION NOTE (webgl.siteprompt2): %S is hostname
webgl.siteprompt2=允许 %S 创建 WebGL 上下文？
webgl.siteprompt2.warning=这可能被用于唯一识别您的计算机。
webgl.block=阻止
webgl.block.accesskey=B
webgl.allow2=允许
webgl.allow2.accesskey=A
webgl.remember2=记住此决定
